name: FKPlug
version : 1.0
authour : Dragon
main : fk.dragon.fkplug.Main

commands :
  plugin:
    description: On tente !
    permission: plugin.use
  trad: 
    description: trad
    permission: trad.use

  discord: 
    description: discord message
    permission: discord.use
    
  discordall: 
    description: discord broadcast
    permission: discordall.use

  mumble: 
    description: mumble message
    permission: mumble.use
 
  mumbleall: 
    description: mumble broadcast
    permission: mumbleall.use
    
  toggleTeleport: 
    description: Active la height border 
    permission: toggleTeleport.use

  gm: 
    description: Switch Gamemode plus simplement
    permission: gm.use

  fkrl: 
    description: reload
    permission: fkrl.use
    
  lockinv: 
    description: Verrouille l'inventaire de tout les joueurs
    permission: lockinv.use    

  heal: 
    description: Soigne le joueur
    permission: heal.use    

  lobby:
    description: Téléporte le joueur au spawn du Lobby
    permission: lobby.use

  hub:
    description: Téléporte le joueur au spawn du Hub
    permission: hub.use

    
  spawn:
    description: Téléporte le joueur au spawn du serveur
    permission: spawn.use